### ISSUE TITLE
Certificate rejected/Aborted connection after showing "System Trust Enabled"

### ISSUE THREAD

**Issue by Shporterator** [httptoolkit/httptoolkit-android#22]
Android TV 11, API 30, Magisk 27

User/System Trust is Enabled, but it doesn't seem to be the case

```
Android command [ 'su', '-c', 'am force-stop com.android.chrome' ] returned ``
Android Chrome flags set
Android command [ 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `shell`
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', '-c', 'sh', '/data/local/tmp/htk-root-test.sh' ] returned `root`
Android command [ 'su', 'root', 'sh', '/data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh,/data/local/tmp/htk-root-test.sh
    at C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:19931
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async Promise.all (index 3)
    at async e.getRootCommand (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:21810)
    at async e.AndroidAdbInterceptor.injectSystemCertIfPossible (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:30737)
    at async e.AndroidAdbInterceptor.activate (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:28565)
    at async e.ApiModel.activateInterceptor (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:890:743387)
    at async C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:3509
    at async C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:2198
Android command [ 'su', 'root', 'sh /data/local/tmp/htk-root-test.sh' ] threw Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
Error: Timeout for ADB command su,root,sh /data/local/tmp/htk-root-test.sh
    at C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:19931
    at async Promise.all (index 4)
    at async e.getRootCommand (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:21810)
    at async e.AndroidAdbInterceptor.injectSystemCertIfPossible (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:30737)
    at async e.AndroidAdbInterceptor.activate (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:28565)
    at async e.ApiModel.activateInterceptor (C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:890:743387)
    at async C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:3509
    at async C:\Users\Max\AppData\Local\Programs\httptoolkit\resources\httptoolkit-server\bundle\index.js:944:2198
Cert already installed, nothing to do
Android command [ 'rm', '-f', '/data/local/tmp/htk-root-test.sh' ] returned ``
Android command [ 'su', '-c', 'sh /data/local/tmp/htk-set-chrome-flags.sh' ] returned `Chrome flags script completed`
Chrome flags script completed
```

![Screenshot_19](https://github.com/httptoolkit/httptoolkit-android/assets/31125459/54f9406d-2882-4317-ba7d-ea3329db49dc)

**Comment by pimterry** [comment]
In this case, I suspect the certificate is actually installed correctly (because all those other requests are working) and your issue is due to certificate pinning, or some other kind of network issue.

If the certificate was not installed correctly then _all_ requests except from Chrome and apps that explicitly enable debug certificates (effectively zero - this only really applies if you're the developer of the app) would all fail.

See https://httptoolkit.com/blog/frida-certificate-pinning/ for more details on how certificate pinning works, and what you can do about it.
